site_name: Mithril playground
site_url: https://github.com/MithrilMan/github-actions-playground/
repo_url: https://github.com/MithrilMan/github-actions-playground/
site_author: Mithril Man
copyright: Mithril Man 2021
nav:
    - Home: 'readme.md'
    - 'Bitcoin Shard':
      - Overview: 'bitcoin-shard/readme.md'
      - Network: 'bitcoin-shard/network.md'
    - Issue Tracker: 'https://github.com/MithrilMan/github-actions-playground/issues'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - csharp
docs_dir: docs
site_dir: ./doc_site

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css